apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-miner
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crypto-miner
  template:
    metadata:
      labels:
        app: crypto-miner
    spec:
      containers:
      - name: crypto-miner
        image: docker.io/servethehome/monero_cpu_minergate
