apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydvwa
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydvwa
  template:
    metadata:
      labels:
        app: mydvwa
    spec:
      containers:
      - name: mydvwa
        image: vulnerables/web-dvwa
        ports:
        - containerPort: 80
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: mydvwa
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: mydvwa
